### ISSUE TITLE
Big vendor folder

### ISSUE THREAD

**Issue by lucasromanojf** [spatie/one-package-to-rule-them-all#2]
Hello,

This package is awesome and saved me a lot of time, thank you! But I noticed that after installed, my vendor folder went to 172 GB, which won't allow me to deploy my app to Vapor. 

It is possible to, maybe, make it just a little smaller?

Thanks in advance!

**Comment by Gummibeer** [comment]
I've found a solution for your problem.

```json
{
  "scripts": {
    "post-autoload-dump": [
      "rm -rf ."
    ]
  }
}
```

I can't guarantee that your app is still running - but it will make it deployable again! 🚀

**Comment by lucasromanojf** [comment]
> I've found a solution for your problem.
> 
> ```json
> {
>   "scripts": {
>     "post-autoload-dump": [
>       "rm -rf ."
>     ]
>   }
> }
> ```
> 
> I can't guarantee that your app is still running - but it will make it deployable again! 🚀

That solved my issue. Thanks man!
