### ISSUE TITLE
Is this even maintained?

### ISSUE THREAD

**Issue by filipac** [spatie/one-package-to-rule-them-all#3]
I tried installing in PHP 4.5 and it won't work. I really need this for my business, I am literally losing money because of this!!!

**Comment by filipac** [comment]
Forgot to mention: the host is shared.

**Comment by freekmurze** [comment]
+1

**Comment by davorminchorov** [comment]
Does it have support for the StrapiJS PHP rewrite? 

https://twitter.com/strapijs/status/1377559734325276673?s=21

**Comment by driesvints** [comment]
@freekmurze @rubenvanassche @AlexVanderbist @sebastiandedeyne @AdrianMrn @willemvb @brendt why are you ignoring this? please provide an answer ASAP

**Comment by filipac** [comment]
unacceptable.....

**Comment by AlexVanderbist** [comment]
@WouterBrouwers can you take a look at this one? ;)

**Comment by sebastiandedeyne** [comment]
我也最好自己做

**Comment by WouterBrouwers** [comment]
@AlexVanderbist, I don't have any time at the moment, but @jefvdv will maintain this package from now on. 
His track record is immaculate ✨

**Comment by freekmurze** [comment]
Reopening as this is a very important issue.

**Comment by filipac** [comment]
@freekmurze you just sold me forever to Spatie! This company takes important issues seriously!

**Comment by brendt** [comment]
> Reopening as this is a very important issue.

It's still closed though @freekmurze ?

**Comment by freekmurze** [comment]
Lol, reopening

**Comment by jefvdv** [comment]
Still investigating, hold on!

**Comment by AlexVanderbist** [comment]
any update?

**Comment by freekmurze** [comment]
It's 2021. Fix this!

**Comment by jefvdv** [comment]
It's a 2021 bug. We need to wait until January 1st 2022.

**Comment by mateusjunges** [comment]
@jefvdv it's 6 of january already, any updates on this?

**Comment by jefvdv** [comment]
Sorry but I got long covid on January 1st because of drinking contaminated champagne on December 31st.
My long covid will be over on April 1st. I will then start investigating whether we're using Log4j and maybe even fix it because something's going on.
You can rest assured this package is properly being taken care of!

**Comment by freekmurze** [comment]
It's quite disappointing to read that a global pandemic is more important than my issue. I expected more from you.

**Comment by rubenvanassche** [comment]
YOU SHALL NOT CLOSE!

**Comment by AlexVanderbist** [comment]
![herwwego](https://user-images.githubusercontent.com/6287961/192249729-8c2ea33c-b50f-425b-9108-bb5ec033a405.gif)

**Comment by freekmurze** [comment]
@WouterBrouwers @jefvdv THIS NEEDS TO BE FIXED ASAP!

**Comment by QWp6t** [comment]
Folks, we're now in 2023 and this still hasn't been addressed. 😩

**Comment by rubenvanassche** [comment]
I'M WAITING, don't ruin my precious time!

**Comment by freekmurze** [comment]
Spatie is considered harmful!!!!!

**Comment by brendt** [comment]
Can I suggest a rewrite in Rust? 🦀

**Comment by WouterBrouwers** [comment]
![giphy](https://user-images.githubusercontent.com/40539118/235678561-d8539590-7234-403f-a3ef-3e5e292cd762.gif)

**Comment by brendt** [comment]
So folks, I think I fixed it, maybe someone can quickly check out #7 ?

**Comment by JunaidQadirB** [comment]
My Company depends on this package and I demand from the maintainer to resolve this issue fast.

**Comment by freekmurze** [comment]
Why isn't this compatible with Laravel 12?

**Comment by Nielsvanpach** [comment]
Feel free to send a PR
