### ISSUE TITLE
This package leaks your address

### ISSUE THREAD

**Issue by ConsoleTVs** [spatie/one-package-to-rule-them-all#4]
I was about to sleep when I noticed 13 dwarves knocking on my door. This package has ruined my privacy....

**Comment by ConsoleTVs** [comment]
Update: They are now asking me to feed them. What?

**Comment by chssmith** [comment]
> 
> 
> Update: They are now asking me to feed them. What?

They're dwarves.  Ale.  Lots of ale.

**Comment by freekmurze** [comment]
Run for the hills!
