### ISSUE TITLE
Doesn't include every package in the universe

### ISSUE THREAD

**Issue by cabeeb** [spatie/one-package-to-rule-them-all#5]
I thought this would install every composer package that exists, but it's only Spatie packages. Insanely self-serving.

**Comment by cabeeb** [comment]
Also, doesn't support PHP 8.2?! 😤

**Comment by freekmurze** [comment]
Bump!

**Comment by AlexVanderbist** [comment]
i fixed this in my fork that definitely doesnt include two new bugs and a crypto miner: https://github.com/AlexVanderbist/one-package-to-rule-them-all
